import { getCurrentHub, captureException, flush } from '@sentry/node';
import { logger, isThenable } from '@sentry/utils';
import { proxyFunction, domainify, getActiveDomain } from '../utils.js';

/**
 * Wraps an event function handler adding it error capture and tracing capabilities.
 *
 * @param fn Event handler
 * @param options Options
 * @returns Event handler
 */
function wrapEventFunction(
  fn,
  wrapOptions = {},
) {
  return proxyFunction(fn, f => domainify(_wrapEventFunction(f, wrapOptions)));
}

/** */
function _wrapEventFunction(
  fn,
  wrapOptions = {},
) {
  const options = {
    flushTimeout: 2000,
    ...wrapOptions,
  };
  return (...eventFunctionArguments) => {
    const [data, context, callback] = eventFunctionArguments;

    const hub = getCurrentHub();

    const transaction = hub.startTransaction({
      name: context.eventType,
      op: 'function.gcp.event',
      metadata: { source: 'component' },
    });

    // getCurrentHub() is expected to use current active domain as a carrier
    // since functions-framework creates a domain for each incoming request.
    // So adding of event processors every time should not lead to memory bloat.
    hub.configureScope(scope => {
      scope.setContext('gcp.function.context', { ...context });
      // We put the transaction on the scope so users can attach children to it
      scope.setSpan(transaction);
    });

    const activeDomain = getActiveDomain(); // eslint-disable-line @typescript-eslint/no-non-null-assertion

    const newCallback = activeDomain.bind((...args) => {
      if (args[0] !== null && args[0] !== undefined) {
        captureException(args[0]);
      }
      transaction.finish();

      void flush(options.flushTimeout)
        .then(null, e => {
          (typeof __SENTRY_DEBUG__ === 'undefined' || __SENTRY_DEBUG__) && logger.error(e);
        })
        .then(() => {
          if (typeof callback === 'function') {
            callback(...args);
          }
        });
    });

    if (fn.length > 2) {
      let fnResult;
      try {
        fnResult = (fn )(data, context, newCallback);
      } catch (err) {
        captureException(err);
        throw err;
      }

      if (isThenable(fnResult)) {
        fnResult.then(null, err => {
          captureException(err);
          throw err;
        });
      }

      return fnResult;
    }

    return Promise.resolve()
      .then(() => (fn )(data, context))
      .then(
        result => newCallback(null, result),
        err => newCallback(err, undefined),
      );
  };
}

export { wrapEventFunction };
//# sourceMappingURL=events.js.map
